definitions:
  api.crawlAccountForm:
    properties:
      account_type:
        type: string
    type: object
  api.crawlMsgForm:
    properties:
      account_id:
        type: string
      account_type:
        type: string
      data_id:
        type: integer
      data_type:
        type: string
    type: object
  api.livehouseForm:
    properties:
      ID:
        type: integer
      name:
        type: string
    type: object
  http.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/crawl-accounts:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get multiple accounts
    post:
      consumes:
      - application/json
      parameters:
      - description: created crawl account object
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.crawlAccountForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Add crawl account
  /api/v1/crawl-accounts/{id}:
    delete:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Delete crawl account
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get crawl account
  /api/v1/crawl-accounts/ws/{id}:
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get multiple accounts
  /api/v1/crawl-messages:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get all crawl messages
    post:
      consumes:
      - application/json
      parameters:
      - description: created crawl message
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.crawlMsgForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Adds crawl message
  /api/v1/crawl-messages/{id}:
    delete:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Delete crawl message
    put:
      consumes:
      - application/json
      parameters:
      - description: modify crawl message
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.crawlMsgForm'
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Edit crawl message
  /api/v1/livehouses:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get all livehouse
    post:
      consumes:
      - application/json
      parameters:
      - description: created livehouse object
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.livehouseForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Add a livehouse
  /api/v1/livehouses/{id}:
    delete:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: delete a livehouse
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: get a livehouse
    post:
      consumes:
      - application/json
      parameters:
      - description: created livehouse object
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.livehouseForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Edit a livehouse
swagger: "2.0"
