definitions:
  api.Response:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  api.chromeForm:
    properties:
      ip:
        type: string
      port:
        type: integer
    type: object
  api.crawlAccountForm:
    properties:
      account_type:
        type: string
    type: object
  api.crawlRoutineForm:
    properties:
      account_type:
        type: string
      data_id:
        type: integer
      data_type:
        type: string
      target_account_id:
        type: string
    type: object
  api.crawlTaskForm:
    properties:
      account_type:
        type: string
      cron_spec:
        type: string
      data_id:
        type: integer
      data_type:
        type: string
      target_account_id:
        type: string
    type: object
  api.livehouseForm:
    properties:
      ID:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/bind-instance:
    post:
      consumes:
      - application/json
      parameters:
      - description: form
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.chromeForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Bind a chrome instance
  /api/v1/crawl-accounts:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get multiple accounts
    post:
      consumes:
      - application/json
      parameters:
      - description: created crawl account object
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.crawlAccountForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Add crawl account
  /api/v1/crawl-accounts/{ID}:
    delete:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Delete crawl account
  /api/v1/crawl-accounts/{id}:
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get crawl account
  /api/v1/crawl-accounts/ws/{ID}:
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Crawl account websocket
  /api/v1/crawl-routines:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get all crawl routines
    post:
      consumes:
      - application/json
      parameters:
      - description: created crawl message
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.crawlRoutineForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Adds crawl routine
  /api/v1/crawl-routines/{ID}:
    delete:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Delete crawl routine
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get a crawl routine
    put:
      consumes:
      - application/json
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      - description: edit crawl message
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.crawlRoutineForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Edit crawl routine
  /api/v1/crawl-routines/start/{ID}:
    post:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Start a crawl message
  /api/v1/crawl-tasks:
    post:
      consumes:
      - application/json
      parameters:
      - description: created crawl task
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.crawlTaskForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Adds crawl task
  /api/v1/create-instance:
    post:
      parameters:
      - description: form
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.chromeForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Create a local chrome instance
  /api/v1/instances:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get multiple chrome instances
  /api/v1/livehouses:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Get all livehouse
    post:
      consumes:
      - application/json
      parameters:
      - description: created livehouse object
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.livehouseForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Add a livehouse
  /api/v1/livehouses/{ID}:
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: ID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: get a livehouse
  /api/v1/livehouses/{id}:
    delete:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: delete a livehouse
    put:
      consumes:
      - application/json
      parameters:
      - description: created livehouse object
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.livehouseForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.Response'
      summary: Edit a livehouse
swagger: "2.0"
