definitions:
  api.addCrawlForm:
    properties:
      crawl_type:
        type: string
    type: object
  http.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/crawls:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get multiple accounts
    post:
      consumes:
      - application/json
      parameters:
      - description: created crawl object
        in: body
        name: form
        required: true
        schema:
          $ref: '#/definitions/api.addCrawlForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Add a crawl
  /api/v1/crawls/{id}:
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get a single crawl
swagger: "2.0"
