definitions:
  api.addInstanceForm:
    properties:
      form_data:
        type: string
      headers:
        additionalProperties: true
        type: object
      name:
        type: string
      query_params:
        type: string
      template_id:
        type: integer
    type: object
  api.addTemplateForm:
    properties:
      form_data:
        type: string
      headers:
        additionalProperties: true
        type: object
      http_method:
        type: string
      login_http_method:
        type: string
      login_url:
        type: string
      name:
        type: string
      query_params:
        type: string
      type:
        type: integer
      url:
        type: string
    type: object
  http.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/crawl/{id}:
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get a single crawl instance
  /api/v1/crawlInstances:
    post:
      consumes:
      - application/json
      parameters:
      - description: created instance object
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/api.addInstanceForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Add crawl instance
  /api/v1/crawlInstances/{id}:
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get a single crawl instance
  /api/v1/crawlTemplates:
    post:
      consumes:
      - application/json
      parameters:
      - description: created template object
        in: body
        name: template
        required: true
        schema:
          $ref: '#/definitions/api.addTemplateForm'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Add crawl template
  /api/v1/crawlTemplates/{id}:
    get:
      parameters:
      - default: 1
        description: ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get a single crawl template
  /api/v1/templates:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/http.Response'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.Response'
      summary: Get multiple templates
swagger: "2.0"
